In [1]:
# import necessary libraries
import pandas as pd
import numpy as np
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import warnings
warnings.filterwarnings('ignore')

In [2]:
driver = webdriver.Edge()

In [5]:
# Question 1

In [6]:
#  Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. 
# You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.

In [7]:
# Solution 1

In [8]:
# Opening the website on automated Edge Browser
driver.get('https://www.shine.com/')

In [13]:
# Enter Data Analyst in job title,skills
job_title = driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div/form/div/div[1]/ul/li[1]/div/input')
job_title.send_keys('Data Analyst')

In [14]:
# Enter Bangalore in Location
location = driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div/form/div/div[1]/ul/li[2]/div/input')
location.send_keys('Bangalore')

In [15]:
search =driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div/form/div/div[2]/div/button')
search.submit()

In [16]:
job_title = []
job_location = []
company_name = []
experience_required = []

In [17]:
# Scrape the job titles and store it
titles = driver.find_elements(By.XPATH,'//h2[contains(@itemprop,"name")]')
for i in titles:
    title = i.text
    job_title.append(title)

In [18]:
len(job_title)

20

In [19]:
# Scrape the job location and store it
locations = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
for i in locations:
    location = i.text
    job_location.append(location)

In [20]:
len(job_location)

20

In [21]:
# Scrape the company name and store it

In [22]:
companies = driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]')
for i in companies:
    company = i.text
    company_name.append(company)

In [23]:
len(company_name)

20

In [24]:
# Scrape the Experience Required and store it

In [25]:
experiences = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_jobIcon__3FB1t"]')
for i in experiences:
    experience = i.text
    experience_required.append(experience)

In [26]:
len(experience_required)

20

In [27]:
# Create a Dataframe of scraped data

In [28]:
import pandas as pd

In [29]:
df = pd.DataFrame({'Job Title':job_title,'Location':job_location,'Company':company_name,'Experience':experience_required})
df.head(10)

,Job Title,Location,Company,Experience
0,Lead Data Analyst,Bangalore,ara resources private limited,4 to 9 Yrs
1,Data Analyst,Bangalore\n+3,diraa hr services hiring for mncs,0 to 1 Yr
2,Vacancy For Data Analyst,Bangalore\n+14,yogita staffing solution,0 to 3 Yrs
3,Clinical Data Analyst,Bangalore\n+6,techno endura,0 to 1 Yr
4,Data Management,Bangalore\n+18,future solution centre,15 to >25 Yrs
5,Data Modeler data,Bangalore,boyen haddin consulting and technol...,3 to 6 Yrs
6,Full time Opportunity-Networking Advisor-Cisco...,Bangalore\n+5,ntt data information processing ser...,10 to 20 Yrs
7,Data Modeller,Bangalore,boyen haddin consulting and technol...,3 to 6 Yrs
8,Data Modeler Bangalore,Bangalore,boyen haddin consulting and technol...,3 to 6 Yrs
9,Data Modeler,Bangalore,boyen haddin consulting and technol...,3 to 6 Yrs

In [30]:
# Question 2
# Write a python program to scrape data for “Data Scientist” Job position in“Bangalore” location. 
# You have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data.

In [31]:
# Solution 2

In [32]:
# Opening the website on automated Edge Browser
driver.get('https://www.shine.com/')

In [35]:
# Enter Data Analyst in job title,skills
job_title = driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[1]/ul/li[1]/div/input')
job_title.send_keys('Data Scientist')

In [36]:
# Enter Bangalore in Location
location = driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[1]/ul/li[2]/div/input')
location.send_keys('Bangalore')

In [37]:
search =driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[2]/div/button')
search.submit()

In [38]:
job_title = []
job_location = []
company_name = []

In [39]:
title_tags = driver.find_elements(By.XPATH,'//h2[contains(@itemprop,"name")]')
for i in title_tags:
    title = i.text
    job_title.append(title)

In [40]:
len(job_title)

20

In [41]:
location_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
for i in location_tags:
    location = i.text
    job_location.append(location)

In [42]:
len(job_location)

20

In [43]:
company_tags = driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]')
for i in company_tags:
    company = i.text
    company_name.append(company)

In [44]:
len(company_name)

20

In [45]:
# Create the data frame
df = pd.DataFrame({'Job Title':job_title,'Location':job_location,'Company':company_name})
df.head(10)

,Job Title,Location,Company
0,Data Scientist Recruitment,Bangalore\n+15,renuka interprises
1,Data Scientist Recruitment,Bangalore\n+15,renuka interprises
2,Data Scientist,Bangalore\n+4,acme services private limited
3,Data Scientist,Bangalore,ltimindtree limited
4,Lead Data Scientist/ Principal Data Scientist,Bangalore\n+1,fractal
5,Senior Data Scientist,Bangalore\n+1,neostats
6,Vacancy For Data Scientist Fresher and Experience,Bangalore\n+14,yogita staffing solution
7,Lead Data Scientist,Bangalore\n+1,aereo
8,Data Scientist,Bangalore\n+7,people staffing solutions
9,Data Scientist Urgent Vacancy,Bangalore\n+14,yogita staffing solution

In [46]:
# Question 3
# In this question you have to scrape data using the filters available on the webpage
# You have to use the location and salary filter.
# You have to scrape data for “Data Scientist” designation for first 10 job results.
# You have to scrape the job-title, job-location, company name, experience required. 
# The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs

In [47]:
# Solution 3

In [48]:
driver.get('https://www.shine.com/')

In [51]:
job_title = driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[1]/ul/li[1]/div/input')
job_title.send_keys('Data Scientist')

In [52]:
search = driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[2]/div/button')
search.submit()

In [53]:
location_filter = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[3]/div/div[1]/div/div[2]/div/ul/li[1]/button')
location_filter.click()

In [55]:
search_location = driver.find_element(By.XPATH,'/html/body/div[2]/div/div/div/div[3]/div/div/div/ul/li[1]/input')
search_location.send_keys('Delhi')

In [57]:
select_delhi_loc = driver.find_element(By.XPATH,'/html/body/div[2]/div/div/div/div[3]/div/div/div/ul/li[2]/span/label')
select_delhi_loc.click()

In [59]:
salary_filter = driver.find_element(By.XPATH,'/html/body/div[2]/div/div/div/div[3]/div/ul/li[3]')
salary_filter.click()

In [61]:
select_salary = driver.find_element(By.XPATH,'/html/body/div[2]/div/div/div/div[3]/div/div/div/ul/li[3]/span/label')
select_salary.click()

In [63]:
show_results = driver.find_element(By.XPATH,'/html/body/div[2]/div/div/div/div[4]/button[2]')
show_results.click()

In [64]:
# Scrape the data

In [65]:
job_title = []
job_location = []
company_name = []
experience_required = []

In [66]:
title_tags = driver.find_elements(By.XPATH,'//h2[contains(@itemprop,"name")]')
for i in title_tags:
    title = i.text
    job_title.append(title)

In [67]:
location_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
for i in location_tags:
    location = i.text
    job_location.append(location)

In [68]:
company_tags = driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]')
for i in company_tags:
    company = i.text
    company_name.append(company)

In [69]:
experience_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_jobIcon__3FB1t"]')
for i in experience_tags:
    experience = i.text
    experience_required.append(experience)

In [70]:
df = pd.DataFrame({'Job Title':job_title,'Location':job_location,'Company':company_name,'Experience':experience_required})
df.head(10)

,Job Title,Location,Company,Experience
0,Data Scientist,Delhi\n+4,acme services private limited,3 to 5 Yrs
1,Hiring candidates for Marketing with Fare & Da...,Delhi\n+2,sharda it services,2 to 5 Yrs
2,Hiring for Fare & Data Analyst-Travel process,Delhi\n+2,sharda it services,1 to 6 Yrs
3,Clinical Data Analyst,Delhi\n+6,techno endura,0 to 1 Yr
4,Bioanalytical Research,Delhi\n+6,techno endura,0 to 1 Yr
5,Clinical Data Management,Delhi\n+6,techno endura,0 to 1 Yr
6,Bioanalytical Research Associates,Delhi\n+6,techno endura,0 to 1 Yr
7,Junior Clinical Data Management,Delhi\n+6,techno endura,0 to 1 Yr
8,Clinical Analyst Fresher,Delhi\n+6,techno endura,0 to 1 Yr
9,Data Engineer,Delhi\n+9,future solution centre,10 to 20 Yrs

In [71]:
# Question 4
# Scrape data of first 100 sunglasses listings on flipkart.com

In [72]:
driver.get('http://www.flipkart.com/')

In [73]:
search_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input') 
search_button.send_keys('sunglasses')

In [74]:
click_search_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/button')
click_search_button.submit()

In [81]:
brand_name = []
brand_description = []
brand_price = []
brand_discount = []

In [82]:
while len(brand_name) <= 100:
    name_tags = driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    description_tags = driver.find_elements(By.CLASS_NAME,"IRpwTa")
    price_tags = driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    discount_tags = driver.find_elements(By.XPATH,'//div[@class="_3Ay6Sb"]')
    
    for i in name_tags:
        name = i.text
        brand_name.append(name)
    
    for i in description_tags:
        description = i.text
        brand_description.append(description)
    
    for i in price_tags:
        price = i.text
        brand_price.append(price)
    
    for i in discount_tags:
        discount = i.text
        brand_discount.append(discount)
        
    next_page = driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_page.click()
    time.sleep(3)

In [83]:
print(len(brand_name),
len(brand_description),
len(brand_price),
len(brand_discount))

120 120 120 120

In [84]:
df = pd.DataFrame({'Name':brand_name,'Description':brand_description,'Price':brand_price,'Discount':brand_discount})
df.head(100)

,Name,Description,Price,Discount
0,Eyewearlabs,"Polarized, UV Protection Wayfarer Sunglasses (51)","₹1,236",65% off
1,Nicole Miller,Polarized Butterfly Sunglasses (64),"₹2,499",75% off
2,SRPM,UV Protection Wayfarer Sunglasses (50),₹169,86% off
3,ROADWAY,"UV Protection Wayfarer, Sports, Spectacle , Re...",₹129,90% off
4,ROADWAY,UV Protection Wayfarer Sunglasses (Free Size),₹189,81% off
...,...,...,...,...
95,Rich Club,UV Protection Retro Square Sunglasses (54),₹487,62% off
96,Eyewearlabs,"Polarized, UV Protection Retro Square Sunglass...","₹1,999",44% off
97,Eyewearlabs,"Polarized, UV Protection Round Sunglasses (48)","₹1,999",44% off
98,MRB HUB,"UV Protection, Night Vision Round Sunglasses (...",₹199,66% off
99,Elligator,UV Protection Retro Square Sunglasses (54),₹159,68% off

In [3]:
# Question 5
# Scrape 100 reviews data from flipkart.com for iphone11 phone

In [4]:
# Solution 5

In [5]:
driver.get('https://www.flipkart.com/apple-iphone-11-black-64-gb/p/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYHWAXCG&marketplace=FLIPKART&q=iphone+11+black+64gb&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=organic&iid=734f25b7-af23-47c2-a7db-bde4758cd8cb.MOBFWQ6BXGJCEYNY.SEARCH&ppt=hp&ppn=homepage&ssid=px1h52d9jk0000001707150015860&qH=c8bcf01bd7ceddcb')

In [6]:
rating = []
review_summary = []
full_review = []

In [7]:
all_reviews = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div[1]/div[2]/div[10]/div[7]/div/a/div')
all_reviews.click()

In [8]:
while len(rating) <= 100:
    rating_tags = driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
    review_summary_tags = driver.find_elements(By.XPATH,'//p[@class="_2-N8zT"]')
    full_review_tags = driver.find_elements(By.XPATH,'//div[@class="t-ZTKy"]/div/div')
    for i in rating_tags:
        rating.append(i.text)
    for i in review_summary_tags:
        review_summary.append(i.text)
    for i in full_review_tags:
        full_review.append(i.text)
    next_page = driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_page.click()
    time.sleep(3)

In [9]:
print(len(rating),
     len(review_summary),
     len(full_review))

110 110 110

In [11]:
df = pd.DataFrame({'Rating':rating,'Review Summary':review_summary,'Full Review':full_review})
df.head(100)

,Rating,Review Summary,Full Review
0,5,Perfect product!,V Good all
1,5,Terrific,Very very good
2,5,Best in the market!,Good Camera
3,5,Wonderful,This is amazing at all
4,5,Worth every penny,Feeling awesome after getting the delivery of ...
...,...,...,...
95,5,Fabulous!,It’s very good battery life and display and vi...
96,5,Terrific purchase,Value for money 🖤🖤
97,5,Must buy!,"Go for iPhone 11 , if confused between iPhone ..."
98,5,Super!,Good product 👌I love iPhone
99,5,Simply awesome,Really satisfied with the Product I received.....

In [12]:
# Question 6
# Scrape data forfirst 100 sneakers you find whenyou visit flipkart.com and search for “sneakers” in the search field.
# You have to scrape 3 attributes of each sneaker:
# 1. Brand
# 2. ProductDescription
# 3. Price

In [13]:
driver.get('http://www.flipkart.com/')

In [14]:
search_btn = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input')
search_btn.send_keys('sneakers')

In [15]:
click_btn = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/button')
click_btn.submit()

In [19]:
brand_name = []
brand_desc = []
brand_price = []

In [20]:
while len(brand_name) <= 100:
    brand_name_tags = driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    brand_desc_tags = driver.find_elements(By.CLASS_NAME,"IRpwTa")
    brand_price_tags = driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    for i in brand_name_tags:
        brand_name.append(i.text)
    for i in brand_desc_tags:
        brand_desc.append(i.text)
    for i in brand_price_tags:
        brand_price.append(i.text)
    next_page = driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_page.click()
    time.sleep(3)

In [21]:
print(len(brand_name),len(brand_desc),len(brand_price))

120 120 120

In [22]:
df = pd.DataFrame({'Brand':brand_name,'Description':brand_desc,'Price':brand_price})
df.head(100)

              Brand                                        Description   Price
0              aadi  Lightweight|Comfort|Summer|Trendy Sneakers For...    ₹444
1      K' Footlance                                   Sneakers For Men    ₹385
2         Deals4you                                 Sneakers For Women    ₹299
3          URBANBOX  Trending Stylish Casual Outdoor Sneakers Shoes...    ₹299
4          RED TAPE  Casual Sneaker Shoes for Men | Soft Cushioned ...  ₹1,139
..              ...                                                ...     ...
95             PUMA                     Shuffle Ultra Sneakers For Men  ₹1,849
96             aadi                                   Sneakers For Men    ₹395
97             aadi  Mesh |Lightweight|Comfort|Summer|Trendy|Walkin...    ₹299
98  U.S. POLO ASSN.                           CLARKIN Sneakers For Men  ₹1,279
99         Shoe Lab                                 Sneakers For Women    ₹399

[100 rows x 3 columns]

In [42]:
# Solution 7

In [43]:
driver.get('http://www.amazon.in/')

In [44]:
search_btn = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
search_btn.send_keys('Laptop')

In [46]:
submit_btn = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
submit_btn.submit()

In [47]:
filter = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[19]/span/span[11]/li/span/a/div')
filter.click()

In [48]:
title_tags = driver.find_elements(By.XPATH,'//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"]')
title = []
for i in title_tags[:10]:
    title.append(i.text)

In [49]:
price_tags = driver.find_elements(By.XPATH,'//span[@class="a-price-whole"]')
price = []
for i in price_tags[:10]:
    price.append(i.text)

In [52]:
len(title)

10

In [53]:
len(price)

10

In [66]:
df = pd.DataFrame({'Title':title,'Price':price})
df

                                               Title     Price
0  Lenovo IdeaPad Slim 3 Intel Core i7 12th Gen 1...    62,990
1  Dell G16-7630 Gaming 13th Gen Laptop, Intel i7...  1,66,490
2  Acer Travelmate Business Laptop Intel Core i7-...    49,990
3  MSI Modern 14, Intel 12th Gen. i7-1255U, 36CM ...    49,990
4  ASUS TUF Gaming F15, 15.6"(39.62 cms) FHD 144H...    77,990
5  HP Pavilion 14 11th Gen Intel Core i7 16GB/1TB...  1,19,990
6  MSI CreatorPro M16, Intel 13th Gen. i7-13700H,...    84,899
7  HP Pavilion 14 12th Gen Intel Core i7 16GB SDR...  1,50,802
8  Samsung Galaxy Book3 Core i7 13th Gen 1355U - ...    77,490
9  Lenovo IdeaPad Slim 3 Intel Core i7 12th Gen 1...    81,990

In [3]:
# Question 8
# Write a python program to scrape data for Top 1000 Quotes of All Time.
# The above task will be done in following steps:
# 1. First get the webpagehttps://www.azquotes.com/
# 2. Click on TopQuotes
# 3. Than scrap a) Quote b) Author c) Type Of Quotes

In [3]:
driver.get('http://www.azquotes.com/')

In [4]:
top_quotes_click = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[1]/div/div[3]/ul/li[5]/a')
top_quotes_click.click()

In [9]:
quote = []
author = []
type_quote = []

In [10]:
num_pages = 10
base_url = "https://www.azquotes.com/top_quotes.html?p="
for page in range(1,num_pages + 1):
    quote_tags = driver.find_elements(By.XPATH,'//a[@class="title"]')
    author_tags = driver.find_elements(By.XPATH,'//div[@class="author"]')
    type_quote_tags = driver.find_elements(By.XPATH,'//div[@class="tags"]')
    for i in quote_tags:
        quote.append(i.text)
    for i in author_tags:
        author.append(i.text)
    for i in type_quote_tags:
        type_quote.append(i.text)
    driver.get(base_url + str(page))
    time.sleep(3)

In [11]:
df = pd.DataFrame({'Quote':quote,'Author':author,'Type of Quote':type_quote})
df

,Quote,Author,Type of Quote
0,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
1,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
2,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
3,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
4,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
...,...,...,...
995,To love means loving the unlovable. To forgive...,Gilbert K. Chesterton,"Love, Inspirational, Success"
996,Be brave. Take risks. Nothing can substitute e...,Paulo Coelho,"Encouraging, Courage, Inspiration"
997,"If you really want to do something, you'll fin...",Jim Rohn,"Inspirational, Motivational, Success"
998,It is neither wealth nor splendor; but tranqui...,Thomas Jefferson,"Life, Happiness, Work"
999,A thousand words will not leave so deep an imp...,Henrik Ibsen,"Inspirational, Inspiring, Positivity"

In [12]:
# QUESTION 9

In [3]:
# Write a python program to display list of respected former Prime Ministers of India(i.e. Name, Born-Dead,
# Term of office, Remarks) from https://www.jagranjosh.com/.
# This task will be done in following steps:
# 1. First get the webpagehttps://www.jagranjosh.com/
# 2. Then You have to click on the GK option
# 3. Then click on the List of all Prime Ministers of India
# 4. Then scrap the mentioned data and make theDataFrame.

In [4]:
# SOLUTION 9

In [5]:
driver.get("http://www.jagranjosh.com/")

In [12]:
click_gk = driver.find_element(By.XPATH,'/html/body/div/header/nav/div/div/div[3]/ul/li[3]/a')
click_gk.click()

In [15]:
explore_list = driver.find_element(By.XPATH,'/html/body/div[1]/div[8]/section[5]/div[1]/span/a')
explore_list.click()

In [16]:
pm_list = driver.find_element(By.XPATH,'/html/body/div[1]/main/div[1]/div[1]/section[2]/div/ul/li[10]/article/h3/a')
pm_list.click()

In [17]:
# column headings
heading = []
all_heading = driver.find_elements(By.XPATH,'//div[@class="TableData"]/table//th')
for i in all_heading:
    heading.append(i.text)

In [18]:
heading

['S.N.', 'PM Name', 'Born-Dead', 'Term of office', 'Remark']

In [30]:
# rows
data = []
row_tags = driver.find_elements(By.XPATH,'//div[@class="TableData"]/table//tr')
for tr in row_tags:
    row = [i.text for i in tr.find_elements(By.XPATH,'//td')]
    data.append(row)
print(data)

[['1.', 'Jawahar Lal Nehru', '(1889–1964)', '15 August 1947 to 27 May 1964\n16 years, 286 days', 'The first prime minister of India and the longest-serving PM of India, the first to die in office.', '2.', 'Gulzarilal Nanda (Acting)', '(1898-1998)', '27 May 1964 to 9 June 1964,\n13 days', 'First acting PM of India', '3.', 'Lal Bahadur Shastri', '(1904–1966)', '9 June 1964 to 11 January 1966\n1 year, 216 days', "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965", '4. ', 'Gulzari Lal Nanda  (Acting)', '(1898-1998)', '11 January 1966 to 24 January 1966\n13 days', '-', '5.', 'Indira Gandhi', '(1917–1984)', '24 January 1966 to 24 March 1977\n11 years, 59 days', 'First female Prime Minister of India', '6.', 'Morarji Desai', '(1896–1995)', '24 March 1977 to  28 July 1979 \n2 year, 126 days', 'Oldest to become PM (81 years old) and first to resign from office', '7.', 'Charan Singh', '(1902–1987)', '28 July 1979 to 14 January 1980\n170 days', 'Only PM who did not face the Parliament', '8.', 'Indira Gandhi', '(1917–1984)', '14 January 1980 to 31 October 1984\n4 years, 291 days', 'The first lady who served as PM for the second term', '9.', 'Rajiv Gandhi', '(1944–1991)', '31 October 1984 to 2 December 1989\n5 years, 32 days', 'Youngest to become PM (40 years old)', '10.', 'V. P. Singh', '(1931–2008)', '2 December 1989 to 10 November 1990\n343 days', 'First PM to step down after a vote of no confidence', '11.', 'Chandra Shekhar', '(1927–2007)', '10 November 1990 to 21 June 1991\n223 days', 'He belongs to  Samajwadi Janata Party', '12.', 'P. V. Narasimha Rao', '(1921–2004)', '21 June 1991 to 16 May 1996\n4 years, 330 days', 'First PM from South India', '13.', 'Atal Bihari Vajpayee', '(1924- 2018)', '16 May 1996 to 1 June 1996\n16 days', 'PM for shortest tenure', '14.', 'H. D. Deve Gowda', '(born 1933)', '1 June 1996 to 21 April 1997\n324 days', 'He belongs to  Janata Dal', '15.', 'Inder Kumar Gujral', '(1919–2012)', '21 April 1997 to 19 March 1998 \n332 days', '------', '16.', 'Atal Bihari Vajpayee', '(1924-2018)', '19 March 1998 to 22 May 2004 \n6 years, 64 days', ' The first non-congress PM who completed a full term as PM', '17.', 'Manmohan Singh', '(born 1932)', '22 May 2004 to 26 May 2014   \n10 years, 4 days', ' First Sikh PM', '18.', 'Narendra Modi', '(born 1950)', '26 May 2014 - 2019', '4th Prime Minister of India who served two consecutive tenures', '19.', 'Narendra Modi', '(born 1950)', '30 May 2019- Incumbent', 'First non-congress PM with two consecutive tenures', 'List of all Presidents of India', 'List of Nicknames of Indian Prime Ministers'], ['1.', 'Jawahar Lal Nehru', '(1889–1964)', '15 August 1947 to 27 May 1964\n16 years, 286 days', 'The first prime minister of India and the longest-serving PM of India, the first to die in office.', '2.', 'Gulzarilal Nanda (Acting)', '(1898-1998)', '27 May 1964 to 9 June 1964,\n13 days', 'First acting PM of India', '3.', 'Lal Bahadur Shastri', '(1904–1966)', '9 June 1964 to 11 January 1966\n1 year, 216 days', "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965", '4. ', 'Gulzari Lal Nanda  (Acting)', '(1898-1998)', '11 January 1966 to 24 January 1966\n13 days', '-', '5.', 'Indira Gandhi', '(1917–1984)', '24 January 1966 to 24 March 1977\n11 years, 59 days', 'First female Prime Minister of India', '6.', 'Morarji Desai', '(1896–1995)', '24 March 1977 to  28 July 1979 \n2 year, 126 days', 'Oldest to become PM (81 years old) and first to resign from office', '7.', 'Charan Singh', '(1902–1987)', '28 July 1979 to 14 January 1980\n170 days', 'Only PM who did not face the Parliament', '8.', 'Indira Gandhi', '(1917–1984)', '14 January 1980 to 31 October 1984\n4 years, 291 days', 'The first lady who served as PM for the second term', '9.', 'Rajiv Gandhi', '(1944–1991)', '31 October 1984 to 2 December 1989\n5 years, 32 days', 'Youngest to become PM (40 years old)', '10.', 'V. P. Singh', '(1931–2008)', '2 December 1989 to 10 November 1990\n343 days', 'First PM to step down after a vote of no confidence', '11.', 'Chandra Shekhar', '(1927–2007)', '10 November 1990 to 21 June 1991\n223 days', 'He belongs to  Samajwadi Janata Party', '12.', 'P. V. Narasimha Rao', '(1921–2004)', '21 June 1991 to 16 May 1996\n4 years, 330 days', 'First PM from South India', '13.', 'Atal Bihari Vajpayee', '(1924- 2018)', '16 May 1996 to 1 June 1996\n16 days', 'PM for shortest tenure', '14.', 'H. D. Deve Gowda', '(born 1933)', '1 June 1996 to 21 April 1997\n324 days', 'He belongs to  Janata Dal', '15.', 'Inder Kumar Gujral', '(1919–2012)', '21 April 1997 to 19 March 1998 \n332 days', '------', '16.', 'Atal Bihari Vajpayee', '(1924-2018)', '19 March 1998 to 22 May 2004 \n6 years, 64 days', ' The first non-congress PM who completed a full term as PM', '17.', 'Manmohan Singh', '(born 1932)', '22 May 2004 to 26 May 2014   \n10 years, 4 days', ' First Sikh PM', '18.', 'Narendra Modi', '(born 1950)', '26 May 2014 - 2019', '4th Prime Minister of India who served two consecutive tenures', '19.', 'Narendra Modi', '(born 1950)', '30 May 2019- Incumbent', 'First non-congress PM with two consecutive tenures', 'List of all Presidents of India', 'List of Nicknames of Indian Prime Ministers'], ['1.', 'Jawahar Lal Nehru', '(1889–1964)', '15 August 1947 to 27 May 1964\n16 years, 286 days', 'The first prime minister of India and the longest-serving PM of India, the first to die in office.', '2.', 'Gulzarilal Nanda (Acting)', '(1898-1998)', '27 May 1964 to 9 June 1964,\n13 days', 'First acting PM of India', '3.', 'Lal Bahadur Shastri', '(1904–1966)', '9 June 1964 to 11 January 1966\n1 year, 216 days', "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965", '4. ', 'Gulzari Lal Nanda  (Acting)', '(1898-1998)', '11 January 1966 to 24 January 1966\n13 days', '-', '5.', 'Indira Gandhi', '(1917–1984)', '24 January 1966 to 24 March 1977\n11 years, 59 days', 'First female Prime Minister of India', '6.', 'Morarji Desai', '(1896–1995)', '24 March 1977 to  28 July 1979 \n2 year, 126 days', 'Oldest to become PM (81 years old) and first to resign from office', '7.', 'Charan Singh', '(1902–1987)', '28 July 1979 to 14 January 1980\n170 days', 'Only PM who did not face the Parliament', '8.', 'Indira Gandhi', '(1917–1984)', '14 January 1980 to 31 October 1984\n4 years, 291 days', 'The first lady who served as PM for the second term', '9.', 'Rajiv Gandhi', '(1944–1991)', '31 October 1984 to 2 December 1989\n5 years, 32 days', 'Youngest to become PM (40 years old)', '10.', 'V. P. Singh', '(1931–2008)', '2 December 1989 to 10 November 1990\n343 days', 'First PM to step down after a vote of no confidence', '11.', 'Chandra Shekhar', '(1927–2007)', '10 November 1990 to 21 June 1991\n223 days', 'He belongs to  Samajwadi Janata Party', '12.', 'P. V. Narasimha Rao', '(1921–2004)', '21 June 1991 to 16 May 1996\n4 years, 330 days', 'First PM from South India', '13.', 'Atal Bihari Vajpayee', '(1924- 2018)', '16 May 1996 to 1 June 1996\n16 days', 'PM for shortest tenure', '14.', 'H. D. Deve Gowda', '(born 1933)', '1 June 1996 to 21 April 1997\n324 days', 'He belongs to  Janata Dal', '15.', 'Inder Kumar Gujral', '(1919–2012)', '21 April 1997 to 19 March 1998 \n332 days', '------', '16.', 'Atal Bihari Vajpayee', '(1924-2018)', '19 March 1998 to 22 May 2004 \n6 years, 64 days', ' The first non-congress PM who completed a full term as PM', '17.', 'Manmohan Singh', '(born 1932)', '22 May 2004 to 26 May 2014   \n10 years, 4 days', ' First Sikh PM', '18.', 'Narendra Modi', '(born 1950)', '26 May 2014 - 2019', '4th Prime Minister of India who served two consecutive tenures', '19.', 'Narendra Modi', '(born 1950)', '30 May 2019- Incumbent', 'First non-congress PM with two consecutive tenures', 'List of all Presidents of India', 'List of Nicknames of Indian Prime Ministers'], ['1.', 'Jawahar Lal Nehru', '(1889–1964)', '15 August 1947 to 27 May 1964\n16 years, 286 days', 'The first prime minister of India and the longest-serving PM of India, the first to die in office.', '2.', 'Gulzarilal Nanda (Acting)', '(1898-1998)', '27 May 1964 to 9 June 1964,\n13 days', 'First acting PM of India', '3.', 'Lal Bahadur Shastri', '(1904–1966)', '9 June 1964 to 11 January 1966\n1 year, 216 days', "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965", '4. ', 'Gulzari Lal Nanda  (Acting)', '(1898-1998)', '11 January 1966 to 24 January 1966\n13 days', '-', '5.', 'Indira Gandhi', '(1917–1984)', '24 January 1966 to 24 March 1977\n11 years, 59 days', 'First female Prime Minister of India', '6.', 'Morarji Desai', '(1896–1995)', '24 March 1977 to  28 July 1979 \n2 year, 126 days', 'Oldest to become PM (81 years old) and first to resign from office', '7.', 'Charan Singh', '(1902–1987)', '28 July 1979 to 14 January 1980\n170 days', 'Only PM who did not face the Parliament', '8.', 'Indira Gandhi', '(1917–1984)', '14 January 1980 to 31 October 1984\n4 years, 291 days', 'The first lady who served as PM for the second term', '9.', 'Rajiv Gandhi', '(1944–1991)', '31 October 1984 to 2 December 1989\n5 years, 32 days', 'Youngest to become PM (40 years old)', '10.', 'V. P. Singh', '(1931–2008)', '2 December 1989 to 10 November 1990\n343 days', 'First PM to step down after a vote of no confidence', '11.', 'Chandra Shekhar', '(1927–2007)', '10 November 1990 to 21 June 1991\n223 days', 'He belongs to  Samajwadi Janata Party', '12.', 'P. V. Narasimha Rao', '(1921–2004)', '21 June 1991 to 16 May 1996\n4 years, 330 days', 'First PM from South India', '13.', 'Atal Bihari Vajpayee', '(1924- 2018)', '16 May 1996 to 1 June 1996\n16 days', 'PM for shortest tenure', '14.', 'H. D. Deve Gowda', '(born 1933)', '1 June 1996 to 21 April 1997\n324 days', 'He belongs to  Janata Dal', '15.', 'Inder Kumar Gujral', '(1919–2012)', '21 April 1997 to 19 March 1998 \n332 days', '------', '16.', 'Atal Bihari Vajpayee', '(1924-2018)', '19 March 1998 to 22 May 2004 \n6 years, 64 days', ' The first non-congress PM who completed a full term as PM', '17.', 'Manmohan Singh', '(born 1932)', '22 May 2004 to 26 May 2014   \n10 years, 4 days', ' First Sikh PM', '18.', 'Narendra Modi', '(born 1950)', '26 May 2014 - 2019', '4th Prime Minister of India who served two consecutive tenures', '19.', 'Narendra Modi', '(born 1950)', '30 May 2019- Incumbent', 'First non-congress PM with two consecutive tenures', 'List of all Presidents of India', 'List of Nicknames of Indian Prime Ministers'], ['1.', 'Jawahar Lal Nehru', '(1889–1964)', '15 August 1947 to 27 May 1964\n16 years, 286 days', 'The first prime minister of India and the longest-serving PM of India, the first to die in office.', '2.', 'Gulzarilal Nanda (Acting)', '(1898-1998)', '27 May 1964 to 9 June 1964,\n13 days', 'First acting PM of India', '3.', 'Lal Bahadur Shastri', '(1904–1966)', '9 June 1964 to 11 January 1966\n1 year, 216 days', "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965", '4. ', 'Gulzari Lal Nanda  (Acting)', '(1898-1998)', '11 January 1966 to 24 January 1966\n13 days', '-', '5.', 'Indira Gandhi', '(1917–1984)', '24 January 1966 to 24 March 1977\n11 years, 59 days', 'First female Prime Minister of India', '6.', 'Morarji Desai', '(1896–1995)', '24 March 1977 to  28 July 1979 \n2 year, 126 days', 'Oldest to become PM (81 years old) and first to resign from office', '7.', 'Charan Singh', '(1902–1987)', '28 July 1979 to 14 January 1980\n170 days', 'Only PM who did not face the Parliament', '8.', 'Indira Gandhi', '(1917–1984)', '14 January 1980 to 31 October 1984\n4 years, 291 days', 'The first lady who served as PM for the second term', '9.', 'Rajiv Gandhi', '(1944–1991)', '31 October 1984 to 2 December 1989\n5 years, 32 days', 'Youngest to become PM (40 years old)', '10.', 'V. P. Singh', '(1931–2008)', '2 December 1989 to 10 November 1990\n343 days', 'First PM to step down after a vote of no confidence', '11.', 'Chandra Shekhar', '(1927–2007)', '10 November 1990 to 21 June 1991\n223 days', 'He belongs to  Samajwadi Janata Party', '12.', 'P. V. Narasimha Rao', '(1921–2004)', '21 June 1991 to 16 May 1996\n4 years, 330 days', 'First PM from South India', '13.', 'Atal Bihari Vajpayee', '(1924- 2018)', '16 May 1996 to 1 June 1996\n16 days', 'PM for shortest tenure', '14.', 'H. D. Deve Gowda', '(born 1933)', '1 June 1996 to 21 April 1997\n324 days', 'He belongs to  Janata Dal', '15.', 'Inder Kumar Gujral', '(1919–2012)', '21 April 1997 to 19 March 1998 \n332 days', '------', '16.', 'Atal Bihari Vajpayee', '(1924-2018)', '19 March 1998 to 22 May 2004 \n6 years, 64 days', ' The first non-congress PM who completed a full term as PM', '17.', 'Manmohan Singh', '(born 1932)', '22 May 2004 to 26 May 2014   \n10 years, 4 days', ' First Sikh PM', '18.', 'Narendra Modi', '(born 1950)', '26 May 2014 - 2019', '4th Prime Minister of India who served two consecutive tenures', '19.', 'Narendra Modi', '(born 1950)', '30 May 2019- Incumbent', 'First non-congress PM with two consecutive tenures', 'List of all Presidents of India', 'List of Nicknames of Indian Prime Ministers'], ['1.', 'Jawahar Lal Nehru', '(1889–1964)', '15 August 1947 to 27 May 1964\n16 years, 286 days', 'The first prime minister of India and the longest-serving PM of India, the first to die in office.', '2.', 'Gulzarilal Nanda (Acting)', '(1898-1998)', '27 May 1964 to 9 June 1964,\n13 days', 'First acting PM of India', '3.', 'Lal Bahadur Shastri', '(1904–1966)', '9 June 1964 to 11 January 1966\n1 year, 216 days', "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965", '4. ', 'Gulzari Lal Nanda  (Acting)', '(1898-1998)', '11 January 1966 to 24 January 1966\n13 days', '-', '5.', 'Indira Gandhi', '(1917–1984)', '24 January 1966 to 24 March 1977\n11 years, 59 days', 'First female Prime Minister of India', '6.', 'Morarji Desai', '(1896–1995)', '24 March 1977 to  28 July 1979 \n2 year, 126 days', 'Oldest to become PM (81 years old) and first to resign from office', '7.', 'Charan Singh', '(1902–1987)', '28 July 1979 to 14 January 1980\n170 days', 'Only PM who did not face the Parliament', '8.', 'Indira Gandhi', '(1917–1984)', '14 January 1980 to 31 October 1984\n4 years, 291 days', 'The first lady who served as PM for the second term', '9.', 'Rajiv Gandhi', '(1944–1991)', '31 October 1984 to 2 December 1989\n5 years, 32 days', 'Youngest to become PM (40 years old)', '10.', 'V. P. Singh', '(1931–2008)', '2 December 1989 to 10 November 1990\n343 days', 'First PM to step down after a vote of no confidence', '11.', 'Chandra Shekhar', '(1927–2007)', '10 November 1990 to 21 June 1991\n223 days', 'He belongs to  Samajwadi Janata Party', '12.', 'P. V. Narasimha Rao', '(1921–2004)', '21 June 1991 to 16 May 1996\n4 years, 330 days', 'First PM from South India', '13.', 'Atal Bihari Vajpayee', '(1924- 2018)', '16 May 1996 to 1 June 1996\n16 days', 'PM for shortest tenure', '14.', 'H. D. Deve Gowda', '(born 1933)', '1 June 1996 to 21 April 1997\n324 days', 'He belongs to  Janata Dal', '15.', 'Inder Kumar Gujral', '(1919–2012)', '21 April 1997 to 19 March 1998 \n332 days', '------', '16.', 'Atal Bihari Vajpayee', '(1924-2018)', '19 March 1998 to 22 May 2004 \n6 years, 64 days', ' The first non-congress PM who completed a full term as PM', '17.', 'Manmohan Singh', '(born 1932)', '22 May 2004 to 26 May 2014   \n10 years, 4 days', ' First Sikh PM', '18.', 'Narendra Modi', '(born 1950)', '26 May 2014 - 2019', '4th Prime Minister of India who served two consecutive tenures', '19.', 'Narendra Modi', '(born 1950)', '30 May 2019- Incumbent', 'First non-congress PM with two consecutive tenures', 'List of all Presidents of India', 'List of Nicknames of Indian Prime Ministers'], ['1.', 'Jawahar Lal Nehru', '(1889–1964)', '15 August 1947 to 27 May 1964\n16 years, 286 days', 'The first prime minister of India and the longest-serving PM of India, the first to die in office.', '2.', 'Gulzarilal Nanda (Acting)', '(1898-1998)', '27 May 1964 to 9 June 1964,\n13 days', 'First acting PM of India', '3.', 'Lal Bahadur Shastri', '(1904–1966)', '9 June 1964 to 11 January 1966\n1 year, 216 days', "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965", '4. ', 'Gulzari Lal Nanda  (Acting)', '(1898-1998)', '11 January 1966 to 24 January 1966\n13 days', '-', '5.', 'Indira Gandhi', '(1917–1984)', '24 January 1966 to 24 March 1977\n11 years, 59 days', 'First female Prime Minister of India', '6.', 'Morarji Desai', '(1896–1995)', '24 March 1977 to  28 July 1979 \n2 year, 126 days', 'Oldest to become PM (81 years old) and first to resign from office', '7.', 'Charan Singh', '(1902–1987)', '28 July 1979 to 14 January 1980\n170 days', 'Only PM who did not face the Parliament', '8.', 'Indira Gandhi', '(1917–1984)', '14 January 1980 to 31 October 1984\n4 years, 291 days', 'The first lady who served as PM for the second term', '9.', 'Rajiv Gandhi', '(1944–1991)', '31 October 1984 to 2 December 1989\n5 years, 32 days', 'Youngest to become PM (40 years old)', '10.', 'V. P. Singh', '(1931–2008)', '2 December 1989 to 10 November 1990\n343 days', 'First PM to step down after a vote of no confidence', '11.', 'Chandra Shekhar', '(1927–2007)', '10 November 1990 to 21 June 1991\n223 days', 'He belongs to  Samajwadi Janata Party', '12.', 'P. V. Narasimha Rao', '(1921–2004)', '21 June 1991 to 16 May 1996\n4 years, 330 days', 'First PM from South India', '13.', 'Atal Bihari Vajpayee', '(1924- 2018)', '16 May 1996 to 1 June 1996\n16 days', 'PM for shortest tenure', '14.', 'H. D. Deve Gowda', '(born 1933)', '1 June 1996 to 21 April 1997\n324 days', 'He belongs to  Janata Dal', '15.', 'Inder Kumar Gujral', '(1919–2012)', '21 April 1997 to 19 March 1998 \n332 days', '------', '16.', 'Atal Bihari Vajpayee', '(1924-2018)', '19 March 1998 to 22 May 2004 \n6 years, 64 days', ' The first non-congress PM who completed a full term as PM', '17.', 'Manmohan Singh', '(born 1932)', '22 May 2004 to 26 May 2014   \n10 years, 4 days', ' First Sikh PM', '18.', 'Narendra Modi', '(born 1950)', '26 May 2014 - 2019', '4th Prime Minister of India who served two consecutive tenures', '19.', 'Narendra Modi', '(born 1950)', '30 May 2019- Incumbent', 'First non-congress PM with two consecutive tenures', 'List of all Presidents of India', 'List of Nicknames of Indian Prime Ministers'], ['1.', 'Jawahar Lal Nehru', '(1889–1964)', '15 August 1947 to 27 May 1964\n16 years, 286 days', 'The first prime minister of India and the longest-serving PM of India, the first to die in office.', '2.', 'Gulzarilal Nanda (Acting)', '(1898-1998)', '27 May 1964 to 9 June 1964,\n13 days', 'First acting PM of India', '3.', 'Lal Bahadur Shastri', '(1904–1966)', '9 June 1964 to 11 January 1966\n1 year, 216 days', "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965", '4. ', 'Gulzari Lal Nanda  (Acting)', '(1898-1998)', '11 January 1966 to 24 January 1966\n13 days', '-', '5.', 'Indira Gandhi', '(1917–1984)', '24 January 1966 to 24 March 1977\n11 years, 59 days', 'First female Prime Minister of India', '6.', 'Morarji Desai', '(1896–1995)', '24 March 1977 to  28 July 1979 \n2 year, 126 days', 'Oldest to become PM (81 years old) and first to resign from office', '7.', 'Charan Singh', '(1902–1987)', '28 July 1979 to 14 January 1980\n170 days', 'Only PM who did not face the Parliament', '8.', 'Indira Gandhi', '(1917–1984)', '14 January 1980 to 31 October 1984\n4 years, 291 days', 'The first lady who served as PM for the second term', '9.', 'Rajiv Gandhi', '(1944–1991)', '31 October 1984 to 2 December 1989\n5 years, 32 days', 'Youngest to become PM (40 years old)', '10.', 'V. P. Singh', '(1931–2008)', '2 December 1989 to 10 November 1990\n343 days', 'First PM to step down after a vote of no confidence', '11.', 'Chandra Shekhar', '(1927–2007)', '10 November 1990 to 21 June 1991\n223 days', 'He belongs to  Samajwadi Janata Party', '12.', 'P. V. Narasimha Rao', '(1921–2004)', '21 June 1991 to 16 May 1996\n4 years, 330 days', 'First PM fro

In [28]:
df = pd.DataFrame(data)
df

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
0,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
1,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
2,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
3,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
4,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
5,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
6,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
7,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
8,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
9,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
10,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
11,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
12,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
13,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
14,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
15,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
16,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
17,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
18,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
19,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers
20,1.,Jawahar Lal Nehru,(1889–1964),"15 August 1947 to 27 May 1964\n16 years, 286 days",The first prime minister of India and the long...,2.,Gulzarilal Nanda (Acting),(1898-1998),"27 May 1964 to 9 June 1964,\n13 days",First acting PM of India,...,(born 1950),26 May 2014 - 2019,4th Prime Minister of India who served two con...,19.,Narendra Modi,(born 1950),30 May 2019- Incumbent,First non-congress PM with two consecutive ten...,List of all Presidents of India,List of Nicknames of Indian Prime Ministers

In [31]:
# Question 10
# Write a python program to display list of 50 Most expensive cars in the world (i.e.
# Car name and Price) from https://www.motor1.com/
# This task will be done in following steps:
# 1. First get the webpage https://www.motor1.com/
# 2. Then You have to type in the search bar ’50 most expensive cars’
# 3. Then click on 50 most expensive carsin the world..
# 4. Then scrap the mentioned data and make the dataframe.

In [32]:
# Solution 10

In [33]:
driver.get('https://www.motor1.com/')

In [34]:
search_btn = driver.find_element(By.XPATH,'/html/body/div[10]/div[2]/div/div/div[3]/div/div/button')
search_btn.click()

In [35]:
type = driver.find_element(By.XPATH,'/html/body/div[10]/div[2]/div/div/div[3]/div/div/div/form/input')
type.send_keys('50 most expensive cars')

In [38]:
click_search = driver.find_element(By.XPATH,'/html/body/div[10]/div[2]/div/div/div[3]/div/div/div/form/button[1]')
click_search.click()

In [39]:
exp_cars = driver.find_element(By.XPATH,'/html/body/div[10]/div[9]/div/div[1]/div/div/div[2]/div/div[1]/h3/a')
exp_cars.click()

In [70]:
car_name_tags = driver.find_elements(By.XPATH,'//h3[@class="subheader"]')
car_name = []
for i in car_name_tags:
    car_name.append(i.text)

In [86]:
car_name = car_name[0:50]
car_name

['Aston Martin Valour',
 'McLaren Elva',
 'Czinger 21C',
 'Ferrari Monza',
 'Gordon Murray T.33',
 'Koenigsegg Gemera',
 'Zenvo TSR-S',
 'Hennessey Venom F5',
 'Bentley Bacalar',
 'Hispano Suiza Carmen Boulogne',
 'Bentley Mulliner Batur',
 'Deus Vayanne',
 'SSC Tuatara',
 'Lotus Evija',
 'Aston Martin Vulcan',
 'Delage D12',
 'Ferrari Daytona SP3',
 'McLaren Speedtail',
 'Rimac Nevera',
 'Pagani Utopia',
 'Pininfarina Battista',
 'Gordon Murray T.50',
 'Lamborghini Countach',
 'Mercedes-AMG Project One',
 'Zenvo Aurora',
 'Aston Martin Victor',
 'Hennessey Venom F5 Roadster',
 'Koenigsegg Jesko',
 'Aston Martin Valkyrie',
 'W Motors Lykan Hypersport',
 'McLaren Solus',
 'Lamborghini Sian',
 'Koenigsegg CC850',
 'Bugatti Chiron Super Sport 300+',
 'Lamborghini Veneno',
 'Bugatti Bolide',
 'Pininfarina B95 Speedster',
 'Bugatti Mistral',
 'Pagani Huayra Imola',
 'Bugatti Divo',
 'SP Automotive Chaos',
 'Pagani Codalunga',
 '777 Hypercar',
 'Mercedes-Maybach Exelero',
 'Bugatti Centodieci',
 'Bugatti Chiron Profilée',
 'Rolls-Royce Sweptail',
 'Bugatti La Voiture Noire',
 'Rolls-Royce Boat Tail*',
 'Rolls-Royce La Rose Noire Droptail']

In [80]:
price_tags = driver.find_elements(By.XPATH,'//strong[starts-with(text(), "Price:")] | //strong[starts-with(text(), "$")]')
price = []
for i in price_tags:
    price.append(i.text)

In [81]:
price

['Price: $1.5 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.8 Million',
 'Price: $1.9 Million',
 'Price: $1.9 Million',
 'Price: $2.0 Million',
 'Price: $2.0 Million',
 'Price: $2.0 Million',
 'Price: $2.1 Million',
 'Price: $2.3 Million',
 'Price: $2.3 Million',
 'Price: $2.3 Million',
 'Price: $2.3 Million',
 'Price: $2.4 Million',
 'Price: $2.5 Million',
 'Price: $2.5 Million',
 'Price: $2.6 Million',
 'Price: $2.6 Million',
 'Price: $2.7 Million',
 'Price: $2.8 Million',
 'Price: $3.0 Million',
 '$3.0 Million',
 'Price: $3.0 Million',
 'Price: $3.2 Million',
 'Price: $3.4 Million',
 '$3.5 Million',
 'Price: $3.6 million',
 'Price: $3.7 Million',
 'Price: $3.9 Million',
 'Price: $4.5 Million',
 'Price: $4.7 Million',
 'Price: $4.8 Million',
 'Price: $5.0 Million',
 'Price: $5.4 Million',
 'Price: $5.8 Million',
 'Price: $6.4 Million',
 'Price: $7.4 Million',
 'Price: $7.5 Million',
 'Price: $8.0 Million',
 'Price: $9.0 Million',
 'Price: $10.8 Million',
 'Price: $12.8 Million',
 'Price: $13.4 Million',
 'Price: $28.0 Million (est.)',
 'Price: $30 Million (est.)']

In [82]:
len(price)

50

In [87]:
len(car_name)

50

In [88]:
df = pd.DataFrame({'Car Name':car_name,'Price':price})
df

                              Car Name                        Price
0                  Aston Martin Valour          Price: $1.5 Million
1                         McLaren Elva          Price: $1.7 Million
2                          Czinger 21C          Price: $1.7 Million
3                        Ferrari Monza          Price: $1.7 Million
4                   Gordon Murray T.33          Price: $1.7 Million
5                    Koenigsegg Gemera          Price: $1.7 Million
6                          Zenvo TSR-S          Price: $1.7 Million
7                   Hennessey Venom F5          Price: $1.8 Million
8                      Bentley Bacalar          Price: $1.9 Million
9        Hispano Suiza Carmen Boulogne          Price: $1.9 Million
10              Bentley Mulliner Batur          Price: $2.0 Million
11                        Deus Vayanne          Price: $2.0 Million
12                         SSC Tuatara          Price: $2.0 Million
13                         Lotus Evija          Price: $2.1 Million
14                 Aston Martin Vulcan          Price: $2.3 Million
15                          Delage D12          Price: $2.3 Million
16                 Ferrari Daytona SP3          Price: $2.3 Million
17                   McLaren Speedtail          Price: $2.3 Million
18                        Rimac Nevera          Price: $2.4 Million
19                       Pagani Utopia          Price: $2.5 Million
20                Pininfarina Battista          Price: $2.5 Million
21                  Gordon Murray T.50          Price: $2.6 Million
22                Lamborghini Countach          Price: $2.6 Million
23            Mercedes-AMG Project One          Price: $2.7 Million
24                        Zenvo Aurora          Price: $2.8 Million
25                 Aston Martin Victor          Price: $3.0 Million
26         Hennessey Venom F5 Roadster                 $3.0 Million
27                    Koenigsegg Jesko          Price: $3.0 Million
28               Aston Martin Valkyrie          Price: $3.2 Million
29           W Motors Lykan Hypersport          Price: $3.4 Million
30                       McLaren Solus                 $3.5 Million
31                    Lamborghini Sian          Price: $3.6 million
32                    Koenigsegg CC850          Price: $3.7 Million
33     Bugatti Chiron Super Sport 300+          Price: $3.9 Million
34                  Lamborghini Veneno          Price: $4.5 Million
35                      Bugatti Bolide          Price: $4.7 Million
36           Pininfarina B95 Speedster          Price: $4.8 Million
37                     Bugatti Mistral          Price: $5.0 Million
38                 Pagani Huayra Imola          Price: $5.4 Million
39                        Bugatti Divo          Price: $5.8 Million
40                 SP Automotive Chaos          Price: $6.4 Million
41                    Pagani Codalunga          Price: $7.4 Million
42                        777 Hypercar          Price: $7.5 Million
43            Mercedes-Maybach Exelero          Price: $8.0 Million
44                  Bugatti Centodieci          Price: $9.0 Million
45             Bugatti Chiron Profilée         Price: $10.8 Million
46                Rolls-Royce Sweptail         Price: $12.8 Million
47            Bugatti La Voiture Noire         Price: $13.4 Million
48              Rolls-Royce Boat Tail*  Price: $28.0 Million (est.)
49  Rolls-Royce La Rose Noire Droptail    Price: $30 Million (est.)